[package]
name = "scorefall-studio"
version = "0.1.0"
authors = ["Jeron Aldaron Lau <jeronlau@plopgrizzly.com>", "Douglas Lau <doug.p.lau@gmail.com>"]
edition = "2018"

[dependencies]
stdweb = "0.4"
score2svg = { path = "../score2svg" }
scorefall = { path = "../scorefall" }
